// Dados fictícios
export const single = [
  {"name": "Nassau - Bloco A", "value": 2563},
  {"name": "Nassau - Bloco B", "value": 452},
  {"name": "Nassau - Bloco C", "value": 8454}
];

export const multi = [
  {
    "name": "Nassau - Bloco A",
    "series": [
      {"name": "2020", "value": 6200},
      {"name": "2021", "value": 651},
      {"name": "2022", "value": 878},
      {"name": "2023", "value": 51446}
    ]
  },
  {
    "name": "Nassau - Bloco B",
    "series": [
      {"name": "2020", "value": 5500},
      {"name": "2021", "value": 484},
      {"name": "2022", "value": 8748},
      {"name": "2023", "value": 95419}
    ]
  },
  {
    "name": "Nassau - Bloco C",
    "series": [
      {"name": "2020", "value": 498},
      {"name": "2021", "value": 5459},
      {"name": "2022", "value": 451},
      {"name": "2023", "value": 745}
    ]
  }
];

export const genderCrimeData = [
  {
    "country": "Nassau - Bloco A",
    "data": [
      {"name": "Homens", "value": 600000},
      {"name": "Mulheres", "value": 300000}
    ]
  },
  {
    "country": "Nassau - Bloco B",
    "data": [
      {"name": "Homens", "value": 400000},
      {"name": "Mulheres", "value": 100000}
    ]
  },
  {
    "country": "Nassau - Bloco C",
    "data": [
      {"name": "Homens", "value": 500000},
      {"name": "Mulheres", "value": 220000}
    ]
  }
];

export const allData = [
  {
    "id": 1,
    "dia": "2024-06-01",
    "hora": "10:30:00",
    "vitima": "João Silva",
    "email": "joao.silva@example.com",
    "telefone": "11987654321",
    "estado": "SP",
    "relato": "Foi empurrado na escola.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 2,
    "dia": "2024-06-02",
    "hora": "11:00:00",
    "vitima": "Maria Oliveira",
    "email": "maria.oliveira@example.com",
    "telefone": "11987654322",
    "estado": "RJ",
    "relato": "Foi chamada de nomes ofensivos.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Parque",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 3,
    "dia": "2024-06-03",
    "hora": "09:15:00",
    "vitima": "Carlos Souza",
    "email": "carlos.souza@example.com",
    "telefone": "11987654323",
    "estado": "MG",
    "relato": "Recebeu ameaças online.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 4,
    "dia": "2024-06-04",
    "hora": "14:45:00",
    "vitima": "Ana Costa",
    "email": "ana.costa@example.com",
    "telefone": "11987654324",
    "estado": "BA",
    "relato": "Foi excluída de atividades em grupo.",
    "generoVitima": "Feminino",
    "relator": "Irmã",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 5,
    "dia": "2024-06-05",
    "hora": "08:50:00",
    "vitima": "Pedro Lima",
    "email": "pedro.lima@example.com",
    "telefone": "11987654325",
    "estado": "PR",
    "relato": "Teve seus pertences danificados.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Físico",
    "tipoLocal": "Transporte Escolar",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 6,
    "dia": "2024-06-06",
    "hora": "12:30:00",
    "vitima": "Lucas Ferreira",
    "email": "lucas.ferreira@example.com",
    "telefone": "11987654326",
    "estado": "RS",
    "relato": "Foi humilhado publicamente.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Shopping",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 7,
    "dia": "2024-06-07",
    "hora": "13:20:00",
    "vitima": "Larissa Almeida",
    "email": "larissa.almeida@example.com",
    "telefone": "11987654327",
    "estado": "PE",
    "relato": "Recebeu mensagens ofensivas.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 8,
    "dia": "2024-06-08",
    "hora": "16:00:00",
    "vitima": "Bruna Martins",
    "email": "bruna.martins@example.com",
    "telefone": "11987654328",
    "estado": "SC",
    "relato": "Foi excluída socialmente.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 9,
    "dia": "2024-06-09",
    "hora": "15:45:00",
    "vitima": "Felipe Santos",
    "email": "felipe.santos@example.com",
    "telefone": "11987654329",
    "estado": "ES",
    "relato": "Teve suas redes sociais hackeadas.",
    "generoVitima": "Masculino",
    "relator": "Irmão",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 10,
    "dia": "2024-06-10",
    "hora": "11:10:00",
    "vitima": "Mariana Lima",
    "email": "mariana.lima@example.com",
    "telefone": "11987654330",
    "estado": "GO",
    "relato": "Foi alvo de piadas constantes.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 11,
    "dia": "2024-06-11",
    "hora": "14:20:00",
    "vitima": "Rodrigo Azevedo",
    "email": "rodrigo.azevedo@example.com",
    "telefone": "11987654331",
    "estado": "MT",
    "relato": "Foi empurrado na fila do lanche.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 12,
    "dia": "2024-06-12",
    "hora": "10:40:00",
    "vitima": "Julia Souza",
    "email": "julia.souza@example.com",
    "telefone": "11987654332",
    "estado": "CE",
    "relato": "Foi vítima de fofocas maldosas.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 13,
    "dia": "2024-06-13",
    "hora": "09:55:00",
    "vitima": "Renato Lima",
    "email": "renato.lima@example.com",
    "telefone": "11987654333",
    "estado": "AL",
    "relato": "Recebeu ameaças de agressão.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Físico",
    "tipoLocal": "Clube",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 14,
    "dia": "2024-06-14",
    "hora": "17:10:00",
    "vitima": "Fernanda Rocha",
    "email": "fernanda.rocha@example.com",
    "telefone": "11987654334",
    "estado": "PI",
    "relato": "Foi alvo de insultos racistas.",
    "generoVitima": "Feminino",
    "relator": "Amigo",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 15,
    "dia": "2024-06-15",
    "hora": "13:30:00",
    "vitima": "Gabriel Souza",
    "email": "gabriel.souza@example.com",
    "telefone": "11987654335",
    "estado": "AM",
    "relato": "Teve seu material escolar roubado.",
    "generoVitima": "Masculino",
    "relator": "Irmã",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 16,
    "dia": "2024-06-16",
    "hora": "14:50:00",
    "vitima": "Natália Costa",
    "email": "natalia.costa@example.com",
    "telefone": "11987654336",
    "estado": "RO",
    "relato": "Foi excluída de conversas.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Social",
    "tipoLocal": "Biblioteca",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 17,
    "dia": "2024-06-17",
    "hora": "12:15:00",
    "vitima": "Thiago Mendes",
    "email": "thiago.mendes@example.com",
    "telefone": "11987654337",
    "estado": "RR",
    "relato": "Recebeu mensagens anônimas ofensivas.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 18,
    "dia": "2024-06-18",
    "hora": "11:35:00",
    "vitima": "Alice Fernandes",
    "email": "alice.fernandes@example.com",
    "telefone": "11987654338",
    "estado": "AC",
    "relato": "Foi alvo de boatos.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 19,
    "dia": "2024-06-19",
    "hora": "09:30:00",
    "vitima": "Marcelo Ribeiro",
    "email": "marcelo.ribeiro@example.com",
    "telefone": "11987654339",
    "estado": "TO",
    "relato": "Foi empurrado no recreio.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 20,
    "dia": "2024-06-20",
    "hora": "10:00:00",
    "vitima": "Camila Lima",
    "email": "camila.lima@example.com",
    "telefone": "11987654340",
    "estado": "AP",
    "relato": "Foi humilhada durante aula.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 21,
    "dia": "2024-06-21",
    "hora": "10:45:00",
    "vitima": "Ricardo Alves",
    "email": "ricardo.alves@example.com",
    "telefone": "11987654341",
    "estado": "PA",
    "relato": "Teve seu lanche roubado.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 22,
    "dia": "2024-06-22",
    "hora": "11:30:00",
    "vitima": "Beatriz Araújo",
    "email": "beatriz.araujo@example.com",
    "telefone": "11987654342",
    "estado": "MA",
    "relato": "Foi excluída de uma festa.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Social",
    "tipoLocal": "Residência",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 23,
    "dia": "2024-06-23",
    "hora": "13:45:00",
    "vitima": "Victor Costa",
    "email": "victor.costa@example.com",
    "telefone": "11987654343",
    "estado": "MS",
    "relato": "Foi ridicularizado por seus colegas.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Clube",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 24,
    "dia": "2024-06-24",
    "hora": "14:00:00",
    "vitima": "Marcos Mendes",
    "email": "marcos.mendes@example.com",
    "telefone": "11987654344",
    "estado": "SE",
    "relato": "Foi alvo de piadas sobre sua aparência.",
    "generoVitima": "Masculino",
    "relator": "Irmão",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 25,
    "dia": "2024-06-25",
    "hora": "16:30:00",
    "vitima": "Larissa Farias",
    "email": "larissa.farias@example.com",
    "telefone": "11987654345",
    "estado": "DF",
    "relato": "Foi excluída de um grupo online.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Social",
    "tipoLocal": "Internet",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 26,
    "dia": "2024-06-26",
    "hora": "17:50:00",
    "vitima": "Gustavo Nunes",
    "email": "gustavo.nunes@example.com",
    "telefone": "11987654346",
    "estado": "GO",
    "relato": "Recebeu mensagens de ódio.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 27,
    "dia": "2024-06-27",
    "hora": "10:25:00",
    "vitima": "Eduarda Lima",
    "email": "eduarda.lima@example.com",
    "telefone": "11987654347",
    "estado": "PE",
    "relato": "Foi deixada de lado pelos colegas.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Social",
    "tipoLocal": "Parque",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 28,
    "dia": "2024-06-28",
    "hora": "12:40:00",
    "vitima": "Bruno Souza",
    "email": "bruno.souza@example.com",
    "telefone": "11987654348",
    "estado": "RJ",
    "relato": "Foi ameaçado fisicamente.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 29,
    "dia": "2024-06-29",
    "hora": "13:10:00",
    "vitima": "Amanda Santos",
    "email": "amanda.santos@example.com",
    "telefone": "11987654349",
    "estado": "SP",
    "relato": "Foi alvo de comentários maldosos.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Shopping",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 30,
    "dia": "2024-06-30",
    "hora": "15:00:00",
    "vitima": "Diego Alves",
    "email": "diego.alves@example.com",
    "telefone": "11987654350",
    "estado": "PR",
    "relato": "Teve seus pertences destruídos.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 31,
    "dia": "2024-07-01",
    "hora": "09:45:00",
    "vitima": "Juliana Araújo",
    "email": "juliana.araujo@example.com",
    "telefone": "11987654351",
    "estado": "MG",
    "relato": "Foi excluída de atividades escolares.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 32,
    "dia": "2024-07-02",
    "hora": "11:15:00",
    "vitima": "Fernando Lima",
    "email": "fernando.lima@example.com",
    "telefone": "11987654352",
    "estado": "SC",
    "relato": "Recebeu ameaças online.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 33,
    "dia": "2024-07-03",
    "hora": "13:50:00",
    "vitima": "Renata Ferreira",
    "email": "renata.ferreira@example.com",
    "telefone": "11987654353",
    "estado": "BA",
    "relato": "Foi alvo de comentários maldosos.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 34,
    "dia": "2024-07-04",
    "hora": "16:10:00",
    "vitima": "Igor Costa",
    "email": "igor.costa@example.com",
    "telefone": "11987654354",
    "estado": "CE",
    "relato": "Foi empurrado na fila do lanche.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 35,
    "dia": "2024-07-05",
    "hora": "10:20:00",
    "vitima": "Tatiana Rocha",
    "email": "tatiana.rocha@example.com",
    "telefone": "11987654355",
    "estado": "ES",
    "relato": "Foi ridicularizada por seus colegas.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Clube",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 36,
    "dia": "2024-07-06",
    "hora": "14:35:00",
    "vitima": "André Almeida",
    "email": "andre.almeida@example.com",
    "telefone": "11987654356",
    "estado": "AL",
    "relato": "Recebeu mensagens ofensivas.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 37,
    "dia": "2024-07-07",
    "hora": "17:00:00",
    "vitima": "Patrícia Martins",
    "email": "patricia.martins@example.com",
    "telefone": "11987654357",
    "estado": "PI",
    "relato": "Foi humilhada durante aula.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 38,
    "dia": "2024-07-08",
    "hora": "09:35:00",
    "vitima": "Thiago Santos",
    "email": "thiago.santos@example.com",
    "telefone": "11987654358",
    "estado": "AM",
    "relato": "Teve seu material escolar danificado.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 39,
    "dia": "2024-07-09",
    "hora": "11:55:00",
    "vitima": "Clara Lima",
    "email": "clara.lima@example.com",
    "telefone": "11987654359",
    "estado": "RO",
    "relato": "Foi alvo de piadas constantes.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 40,
    "dia": "2024-07-10",
    "hora": "13:40:00",
    "vitima": "Rafael Souza",
    "email": "rafael.souza@example.com",
    "telefone": "11987654360",
    "estado": "RR",
    "relato": "Foi excluído de atividades em grupo.",
    "generoVitima": "Masculino",
    "relator": "Irmão",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 41,
    "dia": "2024-07-11",
    "hora": "14:25:00",
    "vitima": "Sabrina Costa",
    "email": "sabrina.costa@example.com",
    "telefone": "11987654361",
    "estado": "AC",
    "relato": "Foi alvo de fofocas maldosas.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 42,
    "dia": "2024-07-12",
    "hora": "10:05:00",
    "vitima": "Paulo Almeida",
    "email": "paulo.almeida@example.com",
    "telefone": "11987654362",
    "estado": "AP",
    "relato": "Recebeu ameaças de agressão.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Físico",
    "tipoLocal": "Clube",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 43,
    "dia": "2024-07-13",
    "hora": "12:20:00",
    "vitima": "Mariana Azevedo",
    "email": "mariana.azevedo@example.com",
    "telefone": "11987654363",
    "estado": "TO",
    "relato": "Foi empurrada na fila do lanche.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 44,
    "dia": "2024-07-14",
    "hora": "16:30:00",
    "vitima": "Lucas Souza",
    "email": "lucas.souza@example.com",
    "telefone": "11987654364",
    "estado": "PA",
    "relato": "Foi alvo de insultos racistas.",
    "generoVitima": "Masculino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 45,
    "dia": "2024-07-15",
    "hora": "09:55:00",
    "vitima": "Rafaela Lima",
    "email": "rafaela.lima@example.com",
    "telefone": "11987654365",
    "estado": "MA",
    "relato": "Foi deixada de lado pelos colegas.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 46,
    "dia": "2024-07-16",
    "hora": "11:45:00",
    "vitima": "Pedro Ferreira",
    "email": "pedro.ferreira@example.com",
    "telefone": "11987654366",
    "estado": "MS",
    "relato": "Foi alvo de zombarias sobre sua aparência.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 47,
    "dia": "2024-07-17",
    "hora": "14:20:00",
    "vitima": "Julia Mendes",
    "email": "julia.mendes@example.com",
    "telefone": "11987654367",
    "estado": "DF",
    "relato": "Recebeu ameaças online.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 48,
    "dia": "2024-07-18",
    "hora": "15:55:00",
    "vitima": "Rodrigo Nunes",
    "email": "rodrigo.nunes@example.com",
    "telefone": "11987654368",
    "estado": "GO",
    "relato": "Foi excluído de atividades escolares.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 49,
    "dia": "2024-07-19",
    "hora": "10:15:00",
    "vitima": "Bruna Costa",
    "email": "bruna.costa@example.com",
    "telefone": "11987654369",
    "estado": "PE",
    "relato": "Foi alvo de boatos.",
    "generoVitima": "Feminino",
    "relator": "Irmã",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 50,
    "dia": "2024-07-20",
    "hora": "12:35:00",
    "vitima": "Renato Silva",
    "email": "renato.silva@example.com",
    "telefone": "11987654370",
    "estado": "RJ",
    "relato": "Recebeu ameaças de agressão.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Fechada"
  }, {
    "id": 51,
    "dia": "2024-07-21",
    "hora": "09:00:00",
    "vitima": "Ana Souza",
    "email": "ana.souza@example.com",
    "telefone": "11987654371",
    "estado": "SP",
    "relato": "Foi excluída de uma festa.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Social",
    "tipoLocal": "Residência",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 52,
    "dia": "2024-07-22",
    "hora": "10:20:00",
    "vitima": "Felipe Oliveira",
    "email": "felipe.oliveira@example.com",
    "telefone": "11987654372",
    "estado": "PR",
    "relato": "Teve seu material escolar roubado.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 53,
    "dia": "2024-07-23",
    "hora": "11:30:00",
    "vitima": "Mariana Dias",
    "email": "mariana.dias@example.com",
    "telefone": "11987654373",
    "estado": "MG",
    "relato": "Foi ridicularizada em público.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 54,
    "dia": "2024-07-24",
    "hora": "14:00:00",
    "vitima": "João Cardoso",
    "email": "joao.cardoso@example.com",
    "telefone": "11987654374",
    "estado": "RS",
    "relato": "Foi alvo de ofensas homofóbicas.",
    "generoVitima": "Masculino",
    "relator": "Mãe",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 55,
    "dia": "2024-07-25",
    "hora": "15:15:00",
    "vitima": "Luana Ribeiro",
    "email": "luana.ribeiro@example.com",
    "telefone": "11987654375",
    "estado": "BA",
    "relato": "Recebeu mensagens de ódio online.",
    "generoVitima": "Feminino",
    "relator": "Irmã",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 56,
    "dia": "2024-07-26",
    "hora": "13:45:00",
    "vitima": "Matheus Santos",
    "email": "matheus.santos@example.com",
    "telefone": "11987654376",
    "estado": "GO",
    "relato": "Foi empurrado no corredor.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 57,
    "dia": "2024-07-27",
    "hora": "16:30:00",
    "vitima": "Carla Almeida",
    "email": "carla.almeida@example.com",
    "telefone": "11987654377",
    "estado": "PE",
    "relato": "Foi alvo de boatos maldosos.",
    "generoVitima": "Feminino",
    "relator": "Amiga",
    "tipoBullying": "Verbal",
    "tipoLocal": "Clube",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 58,
    "dia": "2024-07-28",
    "hora": "17:50:00",
    "vitima": "Pedro Pereira",
    "email": "pedro.pereira@example.com",
    "telefone": "11987654378",
    "estado": "PB",
    "relato": "Recebeu ameaças online.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 59,
    "dia": "2024-07-29",
    "hora": "10:10:00",
    "vitima": "Julia Castro",
    "email": "julia.castro@example.com",
    "telefone": "11987654379",
    "estado": "PA",
    "relato": "Foi humilhada em público.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 60,
    "dia": "2024-07-30",
    "hora": "11:25:00",
    "vitima": "Rodrigo Carvalho",
    "email": "rodrigo.carvalho@example.com",
    "telefone": "11987654380",
    "estado": "CE",
    "relato": "Foi alvo de piadas constantes.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 61,
    "dia": "2024-07-31",
    "hora": "14:40:00",
    "vitima": "Isabela Gomes",
    "email": "isabela.gomes@example.com",
    "telefone": "11987654381",
    "estado": "DF",
    "relato": "Teve seus pertences roubados.",
    "generoVitima": "Feminino",
    "relator": "Irmã",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 62,
    "dia": "2024-08-01",
    "hora": "16:10:00",
    "vitima": "Lucas Rocha",
    "email": "lucas.rocha@example.com",
    "telefone": "11987654382",
    "estado": "MT",
    "relato": "Foi excluído de atividades em grupo.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 63,
    "dia": "2024-08-02",
    "hora": "10:55:00",
    "vitima": "Fernanda Lopes",
    "email": "fernanda.lopes@example.com",
    "telefone": "11987654383",
    "estado": "MS",
    "relato": "Foi alvo de fofocas.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 64,
    "dia": "2024-08-03",
    "hora": "12:30:00",
    "vitima": "Ricardo Martins",
    "email": "ricardo.martins@example.com",
    "telefone": "11987654384",
    "estado": "GO",
    "relato": "Recebeu mensagens de ódio.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 65,
    "dia": "2024-08-04",
    "hora": "13:45:00",
    "vitima": "Gabriela Silva",
    "email": "gabriela.silva@example.com",
    "telefone": "11987654385",
    "estado": "MG",
    "relato": "Foi alvo de zombarias.",
    "generoVitima": "Feminino",
    "relator": "Irmã",
    "tipoBullying": "Verbal",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  }, {
    "id": 66,
    "dia": "2024-08-05",
    "hora": "09:20:00",
    "vitima": "Bruno Santos",
    "email": "bruno.santos@example.com",
    "telefone": "11987654386",
    "estado": "BA",
    "relato": "Foi empurrado na escada.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 67,
    "dia": "2024-08-06",
    "hora": "10:45:00",
    "vitima": "Camila Oliveira",
    "email": "camila.oliveira@example.com",
    "telefone": "11987654387",
    "estado": "RJ",
    "relato": "Foi alvo de insultos.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 68,
    "dia": "2024-08-07",
    "hora": "12:15:00",
    "vitima": "Felipe Alves",
    "email": "felipe.alves@example.com",
    "telefone": "11987654388",
    "estado": "SP",
    "relato": "Teve seus pertences quebrados.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 69,
    "dia": "2024-08-08",
    "hora": "14:30:00",
    "vitima": "Beatriz Lima",
    "email": "beatriz.lima@example.com",
    "telefone": "11987654389",
    "estado": "MG",
    "relato": "Foi alvo de bullying online.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 70,
    "dia": "2024-08-09",
    "hora": "16:00:00",
    "vitima": "Vinícius Silva",
    "email": "vinicius.silva@example.com",
    "telefone": "11987654390",
    "estado": "RJ",
    "relato": "Foi excluído de um grupo de amigos.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 71,
    "dia": "2024-08-10",
    "hora": "09:45:00",
    "vitima": "Eduarda Pereira",
    "email": "eduarda.pereira@example.com",
    "telefone": "11987654391",
    "estado": "PR",
    "relato": "Foi alvo de comentários preconceituosos.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 72,
    "dia": "2024-08-11",
    "hora": "11:20:00",
    "vitima": "Thiago Oliveira",
    "email": "thiago.oliveira@example.com",
    "telefone": "11987654392",
    "estado": "SC",
    "relato": "Foi alvo de brincadeiras humilhantes.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Clube",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 73,
    "dia": "2024-08-12",
    "hora": "13:55:00",
    "vitima": "Maria Oliveira",
    "email": "maria.oliveira@example.com",
    "telefone": "11987654393",
    "estado": "GO",
    "relato": "Foi empurrada no ônibus escolar.",
    "generoVitima": "Feminino",
    "relator": "Amigo",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 74,
    "dia": "2024-08-13",
    "hora": "15:30:00",
    "vitima": "Gabriel Lima",
    "email": "gabriel.lima@example.com",
    "telefone": "11987654394",
    "estado": "SP",
    "relato": "Foi alvo de piadas sobre sua aparência.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 75,
    "dia": "2024-08-14",
    "hora": "17:00:00",
    "vitima": "Amanda Santos",
    "email": "amanda.santos@example.com",
    "telefone": "11987654395",
    "estado": "MG",
    "relato": "Foi alvo de cyberbullying.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  }, {
    "id": 76,
    "dia": "2024-08-15",
    "hora": "09:30:00",
    "vitima": "Lucas Oliveira",
    "email": "lucas.oliveira@example.com",
    "telefone": "11987654396",
    "estado": "RJ",
    "relato": "Foi alvo de discriminação racial.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 77,
    "dia": "2024-08-16",
    "hora": "11:15:00",
    "vitima": "Isabela Silva",
    "email": "isabela.silva@example.com",
    "telefone": "11987654397",
    "estado": "SP",
    "relato": "Foi alvo de perseguição.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 78,
    "dia": "2024-08-17",
    "hora": "13:00:00",
    "vitima": "Pedro Santos",
    "email": "pedro.santos@example.com",
    "telefone": "11987654398",
    "estado": "RS",
    "relato": "Foi alvo de ameaças de violência.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 79,
    "dia": "2024-08-18",
    "hora": "14:45:00",
    "vitima": "Ana Costa",
    "email": "ana.costa@example.com",
    "telefone": "11987654399",
    "estado": "RJ",
    "relato": "Foi alvo de chantagem.",
    "generoVitima": "Feminino",
    "relator": "Amigo",
    "tipoBullying": "Verbal",
    "tipoLocal": "Clube",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 80,
    "dia": "2024-08-19",
    "hora": "16:30:00",
    "vitima": "Mateus Oliveira",
    "email": "mateus.oliveira@example.com",
    "telefone": "11987654400",
    "estado": "SP",
    "relato": "Foi alvo de bullying nas redes sociais.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 81,
    "dia": "2024-08-20",
    "hora": "10:20:00",
    "vitima": "Laura Santos",
    "email": "laura.santos@example.com",
    "telefone": "11987654401",
    "estado": "RS",
    "relato": "Foi alvo de difamação.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Praça",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 82,
    "dia": "2024-08-21",
    "hora": "12:00:00",
    "vitima": "Carlos Silva",
    "email": "carlos.silva@example.com",
    "telefone": "11987654402",
    "estado": "SC",
    "relato": "Foi alvo de agressão física.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 83,
    "dia": "2024-08-22",
    "hora": "14:20:00",
    "vitima": "Juliana Oliveira",
    "email": "juliana.oliveira@example.com",
    "telefone": "11987654403",
    "estado": "SP",
    "relato": "Foi alvo de bullying cibernético.",
    "generoVitima": "Feminino",
    "relator": "Mãe",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 84,
    "dia": "2024-08-23",
    "hora": "16:10:00",
    "vitima": "Gabriel Oliveira",
    "email": "gabriel.oliveira@example.com",
    "telefone": "11987654404",
    "estado": "RJ",
    "relato": "Foi excluído de um grupo de WhatsApp.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Social",
    "tipoLocal": "Internet",
    "statusDenuncia": "Aberta"
  }, {
    "id": 85,
    "dia": "2024-08-25",
    "hora": "18:10:00",
    "vitima": "Rogério Oliveira",
    "email": "rogerio.oliveira@example.com",
    "telefone": "11987654404",
    "estado": "RJ",
    "relato": "Foi excluído de um grupo de WhatsApp.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Social",
    "tipoLocal": "Internet",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 86,
    "dia": "2024-08-25",
    "hora": "11:30:00",
    "vitima": "Pedro Almeida",
    "email": "pedro.almeida@example.com",
    "telefone": "11987654405",
    "estado": "MG",
    "relato": "Foi vítima de bullying físico.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 87,
    "dia": "2024-08-26",
    "hora": "13:15:00",
    "vitima": "Maria Lima",
    "email": "maria.lima@example.com",
    "telefone": "11987654406",
    "estado": "SP",
    "relato": "Sofreu bullying verbal por colegas de classe.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 88,
    "dia": "2024-08-27",
    "hora": "15:00:00",
    "vitima": "Lucas Costa",
    "email": "lucas.costa@example.com",
    "telefone": "11987654407",
    "estado": "RJ",
    "relato": "Foi vítima de cyberbullying.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 89,
    "dia": "2024-08-28",
    "hora": "16:45:00",
    "vitima": "Laura Alves",
    "email": "laura.alves@example.com",
    "telefone": "11987654408",
    "estado": "MG",
    "relato": "Foi intimidada por um grupo de alunos.",
    "generoVitima": "Feminino",
    "relator": "Amigo",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 90,
    "dia": "2024-08-29",
    "hora": "09:40:00",
    "vitima": "Gustavo Pereira",
    "email": "gustavo.pereira@example.com",
    "telefone": "11987654409",
    "estado": "RJ",
    "relato": "Foi alvo de bullying físico no vestiário da escola.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 91,
    "dia": "2024-08-30",
    "hora": "11:20:00",
    "vitima": "Ana Oliveira",
    "email": "ana.oliveira@example.com",
    "telefone": "11987654410",
    "estado": "SP",
    "relato": "Foi alvo de bullying verbal por parte de um colega de classe.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 92,
    "dia": "2024-08-31",
    "hora": "13:00:00",
    "vitima": "Matheus Almeida",
    "email": "matheus.almeida@example.com",
    "telefone": "11987654411",
    "estado": "MG",
    "relato": "Foi intimidado por colegas mais velhos.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 93,
    "dia": "2024-09-01",
    "hora": "14:30:00",
    "vitima": "Amanda Alves",
    "email": "amanda.alves@example.com",
    "telefone": "11987654412",
    "estado": "SP",
    "relato": "Foi alvo de cyberbullying por meio de mensagens ameaçadoras.",
    "generoVitima": "Feminino",
    "relator": "Professor",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Fechada"
  },
  {
    "id": 94,
    "dia": "2024-09-02",
    "hora": "16:15:00",
    "vitima": "Gabriel Almeida",
    "email": "gabriel.almeida@example.com",
    "telefone": "11987654413",
    "estado": "RJ",
    "relato": "Foi vítima de bullying físico durante o recreio.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 95,
    "dia": "2024-09-03",
    "hora": "09:00:00",
    "vitima": "Maria Pereira",
    "email": "maria.pereira@example.com",
    "telefone": "11987654414",
    "estado": "MG",
    "relato": "Foi alvo de bullying verbal por parte de colegas de equipe.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 96,
    "dia": "2024-09-04",
    "hora": "10:45:00",
    "vitima": "Lucas Santos",
    "email": "lucas.santos@example.com",
    "telefone": "11987654415",
    "estado": "SP",
    "relato": "Foi alvo de bullying virtual por meio de comentários depreciativos em suas postagens.",
    "generoVitima": "Masculino",
    "relator": "Amigo",
    "tipoBullying": "Virtual",
    "tipoLocal": "Internet",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 97,
    "dia": "2024-09-05",
    "hora": "12:30:00",
    "vitima": "Ana Silva",
    "email": "ana.silva@example.com",
    "telefone": "11987654416",
    "estado": "RJ",
    "relato": "Foi vítima de bullying físico na saída da escola.",
    "generoVitima": "Feminino",
    "relator": "Pai",
    "tipoBullying": "Físico",
    "tipoLocal": "Escola",
    "statusDenuncia": "Investigação"
  },
  {
    "id": 98,
    "dia": "2024-09-06",
    "hora": "14:15:00",
    "vitima": "Pedro Oliveira",
    "email": "pedro.oliveira@example.com",
    "telefone": "11987654417",
    "estado": "MG",
    "relato": "Foi alvo de bullying verbal por parte de colegas de classe.",
    "generoVitima": "Masculino",
    "relator": "Professor",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 99,
    "dia": "2024-09-07",
    "hora": "16:00:00",
    "vitima": "Maria Oliveira",
    "email": "maria.oliveira@example.com",
    "telefone": "11987654418",
    "estado": "SP",
    "relato": "Foi alvo de bullying social por não ser incluída em atividades extracurriculares.",
    "generoVitima": "Feminino",
    "relator": "Amigo",
    "tipoBullying": "Social",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
  {
    "id": 100,
    "dia": "2024-09-08",
    "hora": "09:45:00",
    "vitima": "Gabriel Lima",
    "email": "gabriel.lima@example.com",
    "telefone": "11987654419",
    "estado": "RJ",
    "relato": "Foi alvo de bullying verbal por parte de um colega de classe.",
    "generoVitima": "Masculino",
    "relator": "Pai",
    "tipoBullying": "Verbal",
    "tipoLocal": "Escola",
    "statusDenuncia": "Aberta"
  },
]
